# Generated by Django 2.1.7 on 2019-07-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='building_to_floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf_id', models.IntegerField(default=0)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='building_user_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bure_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('fcm_token', models.CharField(max_length=256)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='firefighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('fcm_token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.CharField(max_length=100)),
                ('floor_plan', models.ImageField(upload_to='plans/')),
            ],
        ),
        migrations.CreateModel(
            name='floor_to_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn_id', models.IntegerField(default=0)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.floor')),
            ],
        ),
        migrations.CreateModel(
            name='node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('posX', models.IntegerField(default=0)),
                ('posY', models.IntegerField(default=0)),
                ('is_alive', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='floor_to_node',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.node'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='floor_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.floor'),
        ),
        migrations.AddField(
            model_name='building_user_relation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.citizen'),
        ),
        migrations.AddField(
            model_name='building_user_relation',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.building'),
        ),
        migrations.AddField(
            model_name='building_to_floor',
            name='floor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.floor'),
        ),
    ]
