# Generated by Django 2.1.7 on 2019-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20190825_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='gas',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='node',
            name='temperature',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
